# Generated by Django 2.2.9 on 2020-01-11 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(blank=True, help_text='A list with destiny email addresses separated with coma.', max_length=1000, null=True)),
                ('from_email', models.EmailField(help_text="Sender's email address.", max_length=254)),
                ('subject', models.CharField(help_text='Subject text for the mail. Context variable can be used.', max_length=140)),
                ('body', models.TextField(blank=True, help_text='The content of the mail. Context variable can be used.', max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(max_length=200)),
                ('mail_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_mail_template.MailTemplate')),
            ],
        ),
    ]
