# Generated by Django 2.2.9 on 2020-07-27 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_mail_template', '0004_auto_20200721_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(
                blank=True,
                help_text='The content of the mail. Context variable can '
                          'be used.', null=True, verbose_name='Body'),
        ),
    ]
