# Generated by Django 4.0.1 on 2022-03-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mail_template', '0005_auto_20200727_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
